version: '2'
services:
    odosiiservice2-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ODOSIIservice2/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ODOSIIservice2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
